# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admin:
            memory:
                users:
                    admin: { password: secret, roles: [ 'ROLE_ADMIN' ] }
        aimeos_customer:
            entity: { class: AimeosShopBundle:User, property: username }
        in_memory:
            memory: ~

    encoders:
        Aimeos\ShopBundle\Entity\FosUser: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
        Aimeos\ShopBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1


    firewalls:
        aimeos_admin:
            pattern:   ^/admin
            anonymous: ~
            provider: admin
            form_login:
                login_path: /admin
                check_path: /admin_check
        aimeos_myaccount:
            pattern: ^/
            form_login:
                provider: aimeos_customer

            logout:       true
            anonymous:    true


        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/admin/.+, roles: ROLE_ADMIN }
        - { path: ^/myaccount, roles: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/myaccount, roles: ROLE_USER }

